[package]
name = "ants"
version = "0.1.0"
authors = ["Gilles <gilles.rasigade+github@gmail.com>"]
edition = "2018"

[lib]
name = "ants"
path = "src/lib/mod.rs"

[dependencies]
rand = "0.6"

[dev-dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0"